unique_ids:
  assets:
    standard-page.html: ALLTFZANFTAFVLZTZCUWFRXA7TVFRHN6
    theme.css: RTMM7VVAXUSYSTFBMAYAK7DLUL3JHL3X
  forms:
    Form1: PCZRQWXP2GYP2NGXQTVPQMZXVV2I5M5Y
  modules: {}
  scripts: {}
  server_modules: {}
